# Training hyperparameters

batch_size: 4
epochs: 10
fast_dev_run: false
no_dvc_pull: false

# Trainer settings
accelerator: auto
devices: auto

# Checkpoint settings
checkpoint:
  save_top_k: 3
  monitor: val_loss
  mode: min
  filename: "rna-fold-{epoch:02d}-{val_loss:.2f}"
